# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Morgan
email: simon.morgan80@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front end developer and Technical lead with over 10 years digital agency experience.  Focused on responsive front end user interface development.
baseurl: ""
url: "http://simonjohnmorgan.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
